name: Android Release Build

on:
    push:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  cache: gradle

            - name: Grant execute permission for gradlew
              run: chmod +x ./gradlew

            - name: Decode keystore from base64
              run: |
                  echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks

            - name: Build Release APK
              run: ./gradlew assembleRelease
              env:
                  ANDROID_KEYSTORE: keystore.jks
                  ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
                  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
                  ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
                  GH_API_VERSION: ${{ secrets.GH_API_VERSION }}

            - name: Upload Release APK as Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: release-apk
                  path: app/build/outputs/apk/release/*.apk

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              if: github.ref == 'refs/heads/master'
              with:
                  name: "Release ${{ github.run_number }}"
                  tag_name: "v${{ github.run_number }}"
                  files: app/build/outputs/apk/release/*.apk
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Send Email Notification
              uses: dawidd6/action-send-mail@v3
              with:
                  server_address: smtp.gmail.com
                  server_port: 465
                  secure: true
                  username: ${{ secrets.EMAIL_USERNAME }}
                  password: ${{ secrets.EMAIL_PASSWORD }}
                  from: ${{ secrets.EMAIL_USERNAME }}
                  to: multiplatform00@gmail.com,sh.alyyew2019@gmail.com
                  subject: "GHRepo ✅ Android APK Release Build #${{ github.run_number }}"
                  html_body: |
                      <h2>✅ Android APK Build Successful</h2>
                      <p>The APK has been built and published to GitHub Releases.</p>
                      <p><strong>Download it here:</strong></p>
                      <p><a href="https://github.com/${{ github.repository }}/releases/tag/v${{ github.run_number }}">Download APK</a></p>
                      <hr />
                      <p><strong>Last Commit Message:</strong></p>
                      <blockquote>${{ github.event.head_commit.message }}</blockquote>